spring:
  application:
    name: jdbc-example
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  multi-datasources:
    other:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test_other
      initial-size: 1
      max-active: 1


#spring:
#  application:
#    name: jdbc-example
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db01?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#
#  multi-datasources:
#    other:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://43.254.3.72:3306/db01?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: 123456
#      initial-size: 1
#      max-active: 1


devx:
  jdbc:
    base-packages: ["com.william.devx.example.jdbc.dao"]


show-exception: true