spring:
  application:
    name: cache-example
  redis:
    host: localhost
    port: 6379
    database: 0
#    password: Chinawiservqz#
    pool:
        max-active: 10
        max-wait: -1
        max-idle: 1

devx:
  cluster:
    cache: redis


show-exception: true

